\set ON_ERROR_STOP on
begin;
create function pg_temp.check(p boolean,msg text) returns void language plpgsql as $$begin if p is distinct from true then raise exception 'FAIL: %',msg; end if; raise notice 'PASS: %',msg; end$$;
do $$
declare a uuid; b uuid; mgr uuid; project uuid; ib uuid; cv uuid; r jsonb; d jsonb; cmd uuid; msg uuid; before_count int; blocked boolean; lead_id_v uuid; unit_type uuid; unit uuid;
begin
 select id into strict a from auth.users where email='sales.a.test@asher.local';
 select id into strict b from auth.users where email='sales.b.test@asher.local';
 select id into strict mgr from auth.users where email='manager.test@asher.local';
 select id into strict project from core.project where code='asher-naii';
 insert into inbox.inbox(channel,project_id,name) values('line',project,'CONNECT TRANSACTION TEST') returning id into ib;
 perform set_config('request.jwt.claims','{"role":"service_role"}',true);
 set local role service_role;
 r:=inbox.connect_worker('receive',jsonb_build_object('inbox_id',ib,'external_id','test-connect-user','event_id','test-connect-event','text','test inbound','occurred_at',now()-interval '40 minutes'));
 cv:=(r->>'id')::uuid;
 r:=inbox.connect_worker('receive',jsonb_build_object('inbox_id',ib,'external_id','test-connect-user','event_id','test-connect-event','text','duplicate'));
 reset role;
 perform pg_temp.check(r->>'duplicate'='true','duplicate inbound is ignored');
 perform pg_temp.check((select waiting_since<now()-interval '39 minutes' from connect_private.case_state where conversation_id=cv),'SLA starts from inbound timestamp');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);
 perform set_config('request.jwt.claim.sub',a::text,true);
 set local role authenticated;
 r:=inbox.connect_api('list','{"filter":"unassigned"}');
 reset role;
 perform pg_temp.check(exists(select 1 from jsonb_array_elements(r) x where x->>'id'=cv::text),'sales can read unassigned queue');
 cmd:=gen_random_uuid();
 set local role authenticated;
 r:=inbox.connect_api('claim',jsonb_build_object('id',cv,'request_id',cmd));
 d:=inbox.connect_api('claim',jsonb_build_object('id',cv,'request_id',cmd));
 reset role;
 perform pg_temp.check(r=d,'claim replay is idempotent');
 perform pg_temp.check((select assignee_id=a and not bot_active from inbox.conversation where id=cv),'claim owns case and pauses bot');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'role','authenticated')::text,true);
 perform set_config('request.jwt.claim.sub',b::text,true);
 set local role authenticated;
 blocked:=false;begin perform inbox.connect_api('detail',jsonb_build_object('id',cv));exception when insufficient_privilege then blocked:=true;end;
 reset role;
 perform pg_temp.check(blocked,'other sales cannot read claimed case');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);
 perform set_config('request.jwt.claim.sub',a::text,true);
 set local role authenticated;
 d:=inbox.connect_api('detail',jsonb_build_object('id',cv));
 r:=inbox.connect_api('save',jsonb_build_object('id',cv,'request_id',gen_random_uuid(),'version',(d->'state'->>'version')::int,'project_id',project,'display_name','CONNECT TEST','phone','0800000000','budget','2500000','room','1BR','interest','high','follow_up_at',now()+interval '1 day'));
 blocked:=false;begin perform inbox.connect_api('save',jsonb_build_object('id',cv,'request_id',gen_random_uuid(),'version',0,'project_id',project));exception when others then blocked:=sqlerrm='version_conflict';end;
 reset role;
 perform pg_temp.check(blocked,'stale lead edits do not overwrite changes');
 select lead_id into lead_id_v from connect_private.case_state where conversation_id=cv;
 perform pg_temp.check((select budget=2500000 from crm.lead where id=lead_id_v),'profile writes through to ERP lead');
 perform pg_temp.check(exists(select 1 from crm.activity where conversation_id=cv and type='task'),'followup persisted in CRM');
 cmd:=gen_random_uuid();
 set local role authenticated;
 r:=inbox.connect_api('send',jsonb_build_object('id',cv,'request_id',cmd,'text','test outbound'));
 d:=inbox.connect_api('send',jsonb_build_object('id',cv,'request_id',cmd,'text','test outbound'));
 reset role;
 msg:=(r->>'message_id')::uuid;
 perform pg_temp.check(r=d,'send replay returns same message');
 perform pg_temp.check((select count(*)=1 from connect_private.delivery where message_id=msg),'send queues exactly once');
 perform pg_temp.check((select waiting_since is not null from connect_private.case_state where conversation_id=cv),'queued message does not stop SLA');
 perform set_config('request.jwt.claims','{"role":"service_role"}',true);
 set local role service_role;
 d:=inbox.connect_worker('claim',jsonb_build_object('inbox_ids',jsonb_build_array(ib)));
 r:=inbox.connect_worker('finish',jsonb_build_object('message_id',msg,'lease_id',d->>'lease_id','status','sent','provider_id','provider-test'));
 reset role;
 perform pg_temp.check((select waiting_since is null and first_human_response_at is not null from connect_private.case_state where conversation_id=cv),'provider acceptance stops SLA and sets human response');
 perform pg_temp.check(exists(select 1 from core.event_log where entity_id=cv and event_type='message_sent'),'delivery emits ERP event');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);
 set local role authenticated;
 r:=inbox.connect_api('stage',jsonb_build_object('id',cv,'request_id',gen_random_uuid(),'stage','qualified'));
 r:=inbox.connect_api('appointment',jsonb_build_object('id',cv,'request_id',gen_random_uuid(),'appointment_at',now()+interval '1 day'));
 r:=inbox.connect_api('stage',jsonb_build_object('id',cv,'request_id',gen_random_uuid(),'stage','walk_in'));
 reset role;
 perform pg_temp.check((select s.code='walk_in' from crm.lead l join crm.stage s on s.id=l.stage_id where l.id=lead_id_v),'qualified appointment walk-in update ERP stages');
 insert into inventory.unit_type(project_id,code,label,size_sqm,bedrooms,bathrooms,base_price) values(project,'CONNECT-TEST','Connect test',30,1,1,2500000) returning id into unit_type;
 insert into inventory.unit(project_id,unit_type_id,building,floor,number,price) values(project,unit_type,'TEST','1','CONNECT-TEST',2500000) returning id into unit;
 set local role authenticated;
 r:=inbox.connect_api('stage',jsonb_build_object('id',cv,'request_id',gen_random_uuid(),'stage','booking','unit_id',unit,'amount',2500000,'deposit',10000));
 r:=inbox.connect_api('stage',jsonb_build_object('id',cv,'request_id',gen_random_uuid(),'stage','sale','reference','TEST-CONTRACT'));
 reset role;
 perform pg_temp.check(exists(select 1 from doc.booking where lead_id=lead_id_v and status='posted'),'booking creates posted ERP document');
 perform pg_temp.check((select s.code='sale' and l.won_at is not null from crm.lead l join crm.stage s on s.id=l.stage_id where l.id=lead_id_v),'sale marks CRM won');
 perform pg_temp.check((select count(*)>0 from connect_private.audit where conversation_id=cv and action='read'),'read is audited');
end $$;
rollback;
