-- Filename generated by `supabase migration new instagram_inbox`.
-- Registered in this repository's sql/ORDER.txt, not Supabase's migration ledger.
-- Guarded extension of the installed receiver preserves intervening fixes.
DO $migration$
DECLARE
  body text;
  marker text := 'if v_inbox.channel = ''messenger'' then';
BEGIN
  IF (SELECT count(*) FROM pg_attribute WHERE attrelid='inbox.message'::regclass
      AND attname IN ('media','responder_user_id','responder_display_name') AND NOT attisdropped) <> 3 THEN
    RAISE EXCEPTION 'instagram_prerequisites_missing: apply media and responder migrations first';
  END IF;
  body := pg_get_functiondef('connect_private.receive_event(jsonb,timestamptz,integer)'::regprocedure);
  IF position('if v_inbox.channel in (''messenger'', ''instagram'') then' in body) = 0 THEN
    IF position(marker in body) = 0 OR position('ci.channel = ''messenger''' in body) = 0 THEN
      RAISE EXCEPTION 'instagram_receiver_contract_changed: review installed receive_event';
    END IF;
    body := replace(body, marker, 'if v_inbox.channel in (''messenger'', ''instagram'') then');
    body := replace(body, 'ci.channel = ''messenger''', 'ci.channel = v_inbox.channel');
    -- Provider message IDs must only correlate with deliveries in this inbox.
    body := replace(body, 'where d.provider_id = p_data->>''event_id''',
      'where d.provider_id = p_data->>''event_id'' and exists (select 1 from inbox.message dm join inbox.conversation dc on dc.id=dm.conversation_id where dm.id=d.message_id and dc.inbox_id=v_inbox.id)');
    EXECUTE body;
  END IF;
END
$migration$;

-- Unsends clear the visible content and attachment references. The private raw
-- webhook audit continues to follow the existing retention policy.
CREATE OR REPLACE FUNCTION connect_private.instagram_message_deleted(
  p_inbox_id uuid, p_external_id text, p_message_id text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE changed integer;
BEGIN
  UPDATE inbox.message m
     SET content = '[ข้อความถูกยกเลิกใน Instagram]', media = '[]'::jsonb
    FROM inbox.conversation c, inbox.inbox i
   WHERE m.conversation_id = c.id AND c.inbox_id = i.id
     AND i.id = p_inbox_id AND i.channel = 'instagram'
     AND m.external_message_id = p_message_id
     AND EXISTS (SELECT 1 FROM core.contact_identity ci WHERE ci.contact_id=c.contact_id
       AND ci.channel='instagram' AND ci.account_key=i.id::text AND ci.external_id=p_external_id);
  GET DIAGNOSTICS changed = ROW_COUNT;
  RETURN jsonb_build_object('deleted', changed);
END
$function$;
REVOKE ALL ON FUNCTION connect_private.instagram_message_deleted(uuid,text,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION connect_private.instagram_message_deleted(uuid,text,text) TO service_role;
GRANT USAGE ON SCHEMA connect_private TO service_role;
CREATE OR REPLACE FUNCTION inbox.instagram_message_deleted(p_inbox_id uuid, p_external_id text, p_message_id text)
RETURNS jsonb LANGUAGE sql SECURITY INVOKER SET search_path = ''
AS $$ SELECT connect_private.instagram_message_deleted(p_inbox_id,p_external_id,p_message_id); $$;
REVOKE ALL ON FUNCTION inbox.instagram_message_deleted(uuid,text,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION inbox.instagram_message_deleted(uuid,text,text) TO service_role;
NOTIFY pgrst, 'reload schema';

